export default [
  {
    id: 1,
    name: "John Doe",
    last_message: "Hello, how are you?",
    last_message_time: "14:26",
    avatar: require("../../assets/dummyImages/1.png"),
    read_status: "read",
    last_message_sender_id: "MY_ID",
  },
  {
    id: 2,
    name: "Jane Summer",
    last_message: "Where are you?",
    last_message_time: "12:23",
    avatar: require("../../assets/dummyImages/2.png"),
    read_status: "unread",
  },
  {
    id: 3,
    name: "Bob Marley",
    last_message_time: "2/19/23",
    avatar: require("../../assets/dummyImages/3.png"),
    read_status: "unread",
  },
  {
    id: 4,
    name: "Tom Cruise",
    last_message_time: "2/15/23",
    last_message: "Okey then, see you later",
    avatar: require("../../assets/dummyImages/4.png"),
    read_status: "unread",
  },
  {
    id: 5,
    name: "George Clooney",
    last_message_time: "2/11/23",
    last_message: "No, I'm not",
    avatar: require("../../assets/dummyImages/5.png"),
    read_status: "unread",
    last_message_sender_id: "MY_ID",
  },
  {
    id: 6,
    name: "Laura Palmer",
    last_message_time: "2/7/23",
    last_message: "Bye",
    avatar: require("../../assets/dummyImages/6.png"),
    read_status: "read",
    last_message_sender_id: "MY_ID",
  },
  {
    id: 7,
    name: "Frank Sinatra",
    last_message_time: "2/5/23",
    last_message: "Thank you",
    avatar: require("../../assets/dummyImages/7.png"),
    read_status: "read",
    last_message_sender_id: "MY_ID",
  },
  {
    id: 8,
    name: "Lara Croft",
    last_message_time: "2/1/23",
    last_message: "Good bye!",
    avatar: require("../../assets/dummyImages/8.png"),
  },
  {
    id: 9,
    name: "Emely Blunt",
    last_message_time: "1/26/23",
    last_message: "See you later",
    avatar: require("../../assets/dummyImages/9.png"),
  },
  {
    id: 10,
    name: "David Beckham",
    last_message_time: "1/24/23",
    last_message: "Okey bro!",
    avatar: require("../../assets/dummyImages/10.png"),
    read_status: "read",
    last_message_sender_id: "MY_ID",
  },
];
